"""Fixed update api endpoints

Revision ID: 557243c2cc65
Revises: e63ea35a6212
Create Date: 2025-08-31 20:14:20.968914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557243c2cc65'
down_revision: Union[str, None] = 'e63ea35a6212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
